apiVersion: v1
kind: Secret
metadata:
  name: woden-secrets
type: Opaque
data:
  STORAGE_SERVICE_SECRET_KEY: ZGphbmdvLWluc2VjdXJlLW83NiZAKzFyJWJ2anV5XjM3eWFiZXRvNDV3b2IyNnIrK2cteSh5IXUmNTBlZGk1ajZ4
  STORAGE_SERVICE_DB: d29kZW4tc3RvcmFnZQ==
  STORAGE_SERVICE_POSTGRES_USER: d29kZW4tc3RvcmFnZQ==
  STORAGE_SERVICE_POSTGRES_PASSWORD: d29kZW4tc3RvcmFnZQ==